name: Build 1.19

on:
  push:
    branches: [ "1.19" ]
  pull_request:
    branches: [ "1.19" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Chmod Gradle
      run:  chmod +x gradlew 
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Upload a Build Artifact (Fabric)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "Fabric"
        path: fabric/build/libs/*.jar
    - name: Upload a Build Artifact (Forge)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: "Forge"
        path: forge/build/libs/*.jar    
      
